### ISSUE TITLE
No name on taunts

### ISSUE THREAD

**Issue by Fenoyr** [DreamNetwork/gmod-tauntpack#3]
While playing i was unable to see what taunt i was using (all the taunts names were 1, 2, 3, etc... ) so it wasn't easy to know what to pick, i had to write down the ones i already played to know wich one i was using

**Comment by icedream** [comment]
This tauntpack isn't really maintained anymore and is registering the taunts in an old way that is probably now outdated. [It **does** provide names for the taunts](https://github.com/serverkomplex/gmod-tauntpack/blob/master/lua/autorun/server/sv_ph_dreamnetwork_taunts.lua#L37-L173).

Once I will be able to spend some time on this I can get myself up-to-date on this and try to reproduce this so I can fix it.

**Comment by icedream** [comment]
I'll gladly accept pull requests for this by the way.

**Comment by icedream** [comment]
@Fenoyr can you link me which version of Prop Hunt are you using?

**Comment by icedream** [comment]
Closing this as the addon has been updated to support "Prop Hunt: X2Z" instead, and the names work there now.
